version: '2'

services:
    web:
        build: .
        volumes:
            - ./mnt/apache2/conf/vhosts:/usr/local/apache2/conf/vhosts
        ports:
            - 8888:80
            - 443:443
        network_mode: host
